
name: CI - Main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cadquery-version: [2.1, master]
        include-neutronics: [true]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        docker build -t openmc_data_downloader .
        docker run --rm paramak  /bin/bash -c "bash run_tests.sh && curl -s https://codecov.io/bash | bash"
