
name: CI tests
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openmc/openmc:develop

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: Setup package
      run: |
        pip install .

    - name: test_command_line_usage.py
      run: |
        pytest tests/test_command_line_usage.py -v --cov=src --cov-report term --cov-report xml

    - name: test_functions.py
      run: |
        pytest tests/test_functions.py -v --cov=src --cov-report term --cov-report xml

    - name: test_use_in_openmc.py
      run: |
        pytest tests/test_use_in_openmc.py -v --cov=src --cov-report term --cov-report xml

    - name: upload test results
      run: |
        curl -s https://codecov.io/bash | bash
