
name: CI tests
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        mkdir share
        sudo apt-get install -y curl
        docker build -t openmc_data_downloader .
        docker run -v "$PWD/share:/share" openmc_data_downloader
        curl -s https://codecov.io/bash | bash
