
name: CI tests
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        docker build -t openmc_data_downloader .
        docker run --rm -e CI=true -e CODECOV_TOKEN=${{ secrets.PYPI_API_TOKEN }} openmc_data_downloader  /bin/bash -c "bash run_tests.sh && apt-get install curl && bash <(curl -s https://codecov.io/env)"
